# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_pb2 as ai__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIAnalysisServiceStub(object):
    """AI Analysis Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeDaily = channel.unary_unary(
                '/ai.AIAnalysisService/AnalyzeDaily',
                request_serializer=ai__pb2.DailyAnalysisRequest.SerializeToString,
                response_deserializer=ai__pb2.AnalysisResult.FromString,
                _registered_method=True)
        self.AnalyzeWeekly = channel.unary_unary(
                '/ai.AIAnalysisService/AnalyzeWeekly',
                request_serializer=ai__pb2.WeeklyAnalysisRequest.SerializeToString,
                response_deserializer=ai__pb2.AnalysisResult.FromString,
                _registered_method=True)
        self.AnalyzeWritingStyle = channel.unary_unary(
                '/ai.AIAnalysisService/AnalyzeWritingStyle',
                request_serializer=ai__pb2.WritingStyleRequest.SerializeToString,
                response_deserializer=ai__pb2.WritingStyleResult.FromString,
                _registered_method=True)
        self.GetMovieRecommendations = channel.unary_unary(
                '/ai.AIAnalysisService/GetMovieRecommendations',
                request_serializer=ai__pb2.MovieRecommendationRequest.SerializeToString,
                response_deserializer=ai__pb2.MovieRecommendationResult.FromString,
                _registered_method=True)


class AIAnalysisServiceServicer(object):
    """AI Analysis Service
    """

    def AnalyzeDaily(self, request, context):
        """Analyze a single day's journal notes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeWeekly(self, request, context):
        """Analyze a week based on daily summaries
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeWritingStyle(self, request, context):
        """Analyze writing style and find author doppelgänger
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMovieRecommendations(self, request, context):
        """Get movie recommendations based on mood analysis
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIAnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeDaily': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeDaily,
                    request_deserializer=ai__pb2.DailyAnalysisRequest.FromString,
                    response_serializer=ai__pb2.AnalysisResult.SerializeToString,
            ),
            'AnalyzeWeekly': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeWeekly,
                    request_deserializer=ai__pb2.WeeklyAnalysisRequest.FromString,
                    response_serializer=ai__pb2.AnalysisResult.SerializeToString,
            ),
            'AnalyzeWritingStyle': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeWritingStyle,
                    request_deserializer=ai__pb2.WritingStyleRequest.FromString,
                    response_serializer=ai__pb2.WritingStyleResult.SerializeToString,
            ),
            'GetMovieRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMovieRecommendations,
                    request_deserializer=ai__pb2.MovieRecommendationRequest.FromString,
                    response_serializer=ai__pb2.MovieRecommendationResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.AIAnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.AIAnalysisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIAnalysisService(object):
    """AI Analysis Service
    """

    @staticmethod
    def AnalyzeDaily(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIAnalysisService/AnalyzeDaily',
            ai__pb2.DailyAnalysisRequest.SerializeToString,
            ai__pb2.AnalysisResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeWeekly(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIAnalysisService/AnalyzeWeekly',
            ai__pb2.WeeklyAnalysisRequest.SerializeToString,
            ai__pb2.AnalysisResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeWritingStyle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIAnalysisService/AnalyzeWritingStyle',
            ai__pb2.WritingStyleRequest.SerializeToString,
            ai__pb2.WritingStyleResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMovieRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIAnalysisService/GetMovieRecommendations',
            ai__pb2.MovieRecommendationRequest.SerializeToString,
            ai__pb2.MovieRecommendationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
