<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai.proto

namespace GPBMetadata;

class Ai
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ò
ai.protoai"U
DailyAnalysisRequest
user_id (	
date (	
notes (2.ai.JournalNote"y
WeeklyAnalysisRequest
user_id (	

week_start (	
week_end (	)
daily_summaries (2.ai.DailySummary"J
JournalNote

id (
title (	
body (	

created_at (	"ê
DailySummary
date (	
summary (	
dominant_mood (	

mood_score (

highlights (	
advice (	

note_count ("Ö
AnalysisResult
summary (	
dominant_mood (	

mood_score (

highlights (	
advice (	
affirmation (	"5
WritingStyleRequest
user_id (	
texts (	"f
AuthorMatch
name (	
nationality (	
score (
description (	
fun_fact (	"¨
WritingStyleResult
total_words (
total_sentences (
avg_sentence_length (
vocabulary_richness (
punctuation_density (
avg_word_length (
detected_language (	
	top_words (	"
	top_match	 (2.ai.AuthorMatch&
other_matches
 (2.ai.AuthorMatch"í
MovieRecommendationRequest
user_id (	
dominant_mood (	

mood_score (
summary (	

highlights (	
affirmation (	"~
	MovieItem
title (	
year (
tagline (	
imdb_id (	
genres (	
reason (	

poster_url (	"Ü
MovieRecommendationResult
category (	

mood_label (	
headline (	
description (	
items (2.ai.MovieItem2≥
AIAnalysisService<
AnalyzeDaily.ai.DailyAnalysisRequest.ai.AnalysisResult>
AnalyzeWeekly.ai.WeeklyAnalysisRequest.ai.AnalysisResultF
AnalyzeWritingStyle.ai.WritingStyleRequest.ai.WritingStyleResultX
GetMovieRecommendations.ai.MovieRecommendationRequest.ai.MovieRecommendationResultbproto3'
        , true);

        static::$is_initialized = true;
    }
}

