<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai.proto

namespace Ai;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Author match info
 *
 * Generated from protobuf message <code>ai.AuthorMatch</code>
 */
class AuthorMatch extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string nationality = 2;</code>
     */
    protected $nationality = '';
    /**
     * 0-100 percentage match
     *
     * Generated from protobuf field <code>float score = 3;</code>
     */
    protected $score = 0.0;
    /**
     * Generated from protobuf field <code>string description = 4;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>string fun_fact = 5;</code>
     */
    protected $fun_fact = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $nationality
     *     @type float $score
     *           0-100 percentage match
     *     @type string $description
     *     @type string $fun_fact
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ai::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string nationality = 2;</code>
     * @return string
     */
    public function getNationality()
    {
        return $this->nationality;
    }

    /**
     * Generated from protobuf field <code>string nationality = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNationality($var)
    {
        GPBUtil::checkString($var, True);
        $this->nationality = $var;

        return $this;
    }

    /**
     * 0-100 percentage match
     *
     * Generated from protobuf field <code>float score = 3;</code>
     * @return float
     */
    public function getScore()
    {
        return $this->score;
    }

    /**
     * 0-100 percentage match
     *
     * Generated from protobuf field <code>float score = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setScore($var)
    {
        GPBUtil::checkFloat($var);
        $this->score = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 4;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fun_fact = 5;</code>
     * @return string
     */
    public function getFunFact()
    {
        return $this->fun_fact;
    }

    /**
     * Generated from protobuf field <code>string fun_fact = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setFunFact($var)
    {
        GPBUtil::checkString($var, True);
        $this->fun_fact = $var;

        return $this;
    }

}

