<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai.proto

namespace Ai;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A daily summary (used for weekly aggregation)
 *
 * Generated from protobuf message <code>ai.DailySummary</code>
 */
class DailySummary extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string date = 1;</code>
     */
    protected $date = '';
    /**
     * Generated from protobuf field <code>string summary = 2;</code>
     */
    protected $summary = '';
    /**
     * Generated from protobuf field <code>string dominant_mood = 3;</code>
     */
    protected $dominant_mood = '';
    /**
     * 0-100
     *
     * Generated from protobuf field <code>int32 mood_score = 4;</code>
     */
    protected $mood_score = 0;
    /**
     * Generated from protobuf field <code>repeated string highlights = 5;</code>
     */
    private $highlights;
    /**
     * Generated from protobuf field <code>repeated string advice = 6;</code>
     */
    private $advice;
    /**
     * Generated from protobuf field <code>int32 note_count = 7;</code>
     */
    protected $note_count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $date
     *     @type string $summary
     *     @type string $dominant_mood
     *     @type int $mood_score
     *           0-100
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $highlights
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $advice
     *     @type int $note_count
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ai::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string date = 1;</code>
     * @return string
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Generated from protobuf field <code>string date = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string summary = 2;</code>
     * @return string
     */
    public function getSummary()
    {
        return $this->summary;
    }

    /**
     * Generated from protobuf field <code>string summary = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSummary($var)
    {
        GPBUtil::checkString($var, True);
        $this->summary = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string dominant_mood = 3;</code>
     * @return string
     */
    public function getDominantMood()
    {
        return $this->dominant_mood;
    }

    /**
     * Generated from protobuf field <code>string dominant_mood = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDominantMood($var)
    {
        GPBUtil::checkString($var, True);
        $this->dominant_mood = $var;

        return $this;
    }

    /**
     * 0-100
     *
     * Generated from protobuf field <code>int32 mood_score = 4;</code>
     * @return int
     */
    public function getMoodScore()
    {
        return $this->mood_score;
    }

    /**
     * 0-100
     *
     * Generated from protobuf field <code>int32 mood_score = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMoodScore($var)
    {
        GPBUtil::checkInt32($var);
        $this->mood_score = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string highlights = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHighlights()
    {
        return $this->highlights;
    }

    /**
     * Generated from protobuf field <code>repeated string highlights = 5;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHighlights($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->highlights = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string advice = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAdvice()
    {
        return $this->advice;
    }

    /**
     * Generated from protobuf field <code>repeated string advice = 6;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAdvice($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->advice = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 note_count = 7;</code>
     * @return int
     */
    public function getNoteCount()
    {
        return $this->note_count;
    }

    /**
     * Generated from protobuf field <code>int32 note_count = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setNoteCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->note_count = $var;

        return $this;
    }

}

