<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai.proto

namespace Ai;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Movie recommendations result
 *
 * Generated from protobuf message <code>ai.MovieRecommendationResult</code>
 */
class MovieRecommendationResult extends \Google\Protobuf\Internal\Message
{
    /**
     * joyful, comfort, grounding, reflective, motivational, balanced
     *
     * Generated from protobuf field <code>string category = 1;</code>
     */
    protected $category = '';
    /**
     * Generated from protobuf field <code>string mood_label = 2;</code>
     */
    protected $mood_label = '';
    /**
     * Generated from protobuf field <code>string headline = 3;</code>
     */
    protected $headline = '';
    /**
     * Generated from protobuf field <code>string description = 4;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>repeated .ai.MovieItem items = 5;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $category
     *           joyful, comfort, grounding, reflective, motivational, balanced
     *     @type string $mood_label
     *     @type string $headline
     *     @type string $description
     *     @type array<\Ai\MovieItem>|\Google\Protobuf\Internal\RepeatedField $items
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ai::initOnce();
        parent::__construct($data);
    }

    /**
     * joyful, comfort, grounding, reflective, motivational, balanced
     *
     * Generated from protobuf field <code>string category = 1;</code>
     * @return string
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * joyful, comfort, grounding, reflective, motivational, balanced
     *
     * Generated from protobuf field <code>string category = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCategory($var)
    {
        GPBUtil::checkString($var, True);
        $this->category = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mood_label = 2;</code>
     * @return string
     */
    public function getMoodLabel()
    {
        return $this->mood_label;
    }

    /**
     * Generated from protobuf field <code>string mood_label = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMoodLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->mood_label = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string headline = 3;</code>
     * @return string
     */
    public function getHeadline()
    {
        return $this->headline;
    }

    /**
     * Generated from protobuf field <code>string headline = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setHeadline($var)
    {
        GPBUtil::checkString($var, True);
        $this->headline = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 4;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .ai.MovieItem items = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .ai.MovieItem items = 5;</code>
     * @param array<\Ai\MovieItem>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ai\MovieItem::class);
        $this->items = $arr;

        return $this;
    }

}

