<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai.proto

namespace Ai;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A single movie recommendation
 *
 * Generated from protobuf message <code>ai.MovieItem</code>
 */
class MovieItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string title = 1;</code>
     */
    protected $title = '';
    /**
     * Generated from protobuf field <code>int32 year = 2;</code>
     */
    protected $year = 0;
    /**
     * Generated from protobuf field <code>string tagline = 3;</code>
     */
    protected $tagline = '';
    /**
     * Generated from protobuf field <code>string imdb_id = 4;</code>
     */
    protected $imdb_id = '';
    /**
     * Generated from protobuf field <code>repeated string genres = 5;</code>
     */
    private $genres;
    /**
     * Generated from protobuf field <code>string reason = 6;</code>
     */
    protected $reason = '';
    /**
     * Generated from protobuf field <code>string poster_url = 7;</code>
     */
    protected $poster_url = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $title
     *     @type int $year
     *     @type string $tagline
     *     @type string $imdb_id
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $genres
     *     @type string $reason
     *     @type string $poster_url
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ai::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 year = 2;</code>
     * @return int
     */
    public function getYear()
    {
        return $this->year;
    }

    /**
     * Generated from protobuf field <code>int32 year = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setYear($var)
    {
        GPBUtil::checkInt32($var);
        $this->year = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tagline = 3;</code>
     * @return string
     */
    public function getTagline()
    {
        return $this->tagline;
    }

    /**
     * Generated from protobuf field <code>string tagline = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTagline($var)
    {
        GPBUtil::checkString($var, True);
        $this->tagline = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string imdb_id = 4;</code>
     * @return string
     */
    public function getImdbId()
    {
        return $this->imdb_id;
    }

    /**
     * Generated from protobuf field <code>string imdb_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setImdbId($var)
    {
        GPBUtil::checkString($var, True);
        $this->imdb_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string genres = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGenres()
    {
        return $this->genres;
    }

    /**
     * Generated from protobuf field <code>repeated string genres = 5;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGenres($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->genres = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string reason = 6;</code>
     * @return string
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * Generated from protobuf field <code>string reason = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->reason = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string poster_url = 7;</code>
     * @return string
     */
    public function getPosterUrl()
    {
        return $this->poster_url;
    }

    /**
     * Generated from protobuf field <code>string poster_url = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setPosterUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->poster_url = $var;

        return $this;
    }

}

