<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai.proto

namespace Ai;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request to analyze weekly journal (from daily summaries)
 *
 * Generated from protobuf message <code>ai.WeeklyAnalysisRequest</code>
 */
class WeeklyAnalysisRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     */
    protected $user_id = '';
    /**
     * ISO date string
     *
     * Generated from protobuf field <code>string week_start = 2;</code>
     */
    protected $week_start = '';
    /**
     * ISO date string
     *
     * Generated from protobuf field <code>string week_end = 3;</code>
     */
    protected $week_end = '';
    /**
     * Generated from protobuf field <code>repeated .ai.DailySummary daily_summaries = 4;</code>
     */
    private $daily_summaries;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $user_id
     *     @type string $week_start
     *           ISO date string
     *     @type string $week_end
     *           ISO date string
     *     @type array<\Ai\DailySummary>|\Google\Protobuf\Internal\RepeatedField $daily_summaries
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ai::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * ISO date string
     *
     * Generated from protobuf field <code>string week_start = 2;</code>
     * @return string
     */
    public function getWeekStart()
    {
        return $this->week_start;
    }

    /**
     * ISO date string
     *
     * Generated from protobuf field <code>string week_start = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setWeekStart($var)
    {
        GPBUtil::checkString($var, True);
        $this->week_start = $var;

        return $this;
    }

    /**
     * ISO date string
     *
     * Generated from protobuf field <code>string week_end = 3;</code>
     * @return string
     */
    public function getWeekEnd()
    {
        return $this->week_end;
    }

    /**
     * ISO date string
     *
     * Generated from protobuf field <code>string week_end = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setWeekEnd($var)
    {
        GPBUtil::checkString($var, True);
        $this->week_end = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .ai.DailySummary daily_summaries = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDailySummaries()
    {
        return $this->daily_summaries;
    }

    /**
     * Generated from protobuf field <code>repeated .ai.DailySummary daily_summaries = 4;</code>
     * @param array<\Ai\DailySummary>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDailySummaries($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ai\DailySummary::class);
        $this->daily_summaries = $arr;

        return $this;
    }

}

