<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai.proto

namespace Ai;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Writing style analysis result
 *
 * Generated from protobuf message <code>ai.WritingStyleResult</code>
 */
class WritingStyleResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 total_words = 1;</code>
     */
    protected $total_words = 0;
    /**
     * Generated from protobuf field <code>int32 total_sentences = 2;</code>
     */
    protected $total_sentences = 0;
    /**
     * Generated from protobuf field <code>float avg_sentence_length = 3;</code>
     */
    protected $avg_sentence_length = 0.0;
    /**
     * 0-1 ratio
     *
     * Generated from protobuf field <code>float vocabulary_richness = 4;</code>
     */
    protected $vocabulary_richness = 0.0;
    /**
     * per 100 words
     *
     * Generated from protobuf field <code>float punctuation_density = 5;</code>
     */
    protected $punctuation_density = 0.0;
    /**
     * Generated from protobuf field <code>float avg_word_length = 6;</code>
     */
    protected $avg_word_length = 0.0;
    /**
     * Generated from protobuf field <code>string detected_language = 7;</code>
     */
    protected $detected_language = '';
    /**
     * Generated from protobuf field <code>repeated string top_words = 8;</code>
     */
    private $top_words;
    /**
     * Generated from protobuf field <code>.ai.AuthorMatch top_match = 9;</code>
     */
    protected $top_match = null;
    /**
     * Generated from protobuf field <code>repeated .ai.AuthorMatch other_matches = 10;</code>
     */
    private $other_matches;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $total_words
     *     @type int $total_sentences
     *     @type float $avg_sentence_length
     *     @type float $vocabulary_richness
     *           0-1 ratio
     *     @type float $punctuation_density
     *           per 100 words
     *     @type float $avg_word_length
     *     @type string $detected_language
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $top_words
     *     @type \Ai\AuthorMatch $top_match
     *     @type array<\Ai\AuthorMatch>|\Google\Protobuf\Internal\RepeatedField $other_matches
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ai::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 total_words = 1;</code>
     * @return int
     */
    public function getTotalWords()
    {
        return $this->total_words;
    }

    /**
     * Generated from protobuf field <code>int32 total_words = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalWords($var)
    {
        GPBUtil::checkInt32($var);
        $this->total_words = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 total_sentences = 2;</code>
     * @return int
     */
    public function getTotalSentences()
    {
        return $this->total_sentences;
    }

    /**
     * Generated from protobuf field <code>int32 total_sentences = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalSentences($var)
    {
        GPBUtil::checkInt32($var);
        $this->total_sentences = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float avg_sentence_length = 3;</code>
     * @return float
     */
    public function getAvgSentenceLength()
    {
        return $this->avg_sentence_length;
    }

    /**
     * Generated from protobuf field <code>float avg_sentence_length = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setAvgSentenceLength($var)
    {
        GPBUtil::checkFloat($var);
        $this->avg_sentence_length = $var;

        return $this;
    }

    /**
     * 0-1 ratio
     *
     * Generated from protobuf field <code>float vocabulary_richness = 4;</code>
     * @return float
     */
    public function getVocabularyRichness()
    {
        return $this->vocabulary_richness;
    }

    /**
     * 0-1 ratio
     *
     * Generated from protobuf field <code>float vocabulary_richness = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setVocabularyRichness($var)
    {
        GPBUtil::checkFloat($var);
        $this->vocabulary_richness = $var;

        return $this;
    }

    /**
     * per 100 words
     *
     * Generated from protobuf field <code>float punctuation_density = 5;</code>
     * @return float
     */
    public function getPunctuationDensity()
    {
        return $this->punctuation_density;
    }

    /**
     * per 100 words
     *
     * Generated from protobuf field <code>float punctuation_density = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setPunctuationDensity($var)
    {
        GPBUtil::checkFloat($var);
        $this->punctuation_density = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float avg_word_length = 6;</code>
     * @return float
     */
    public function getAvgWordLength()
    {
        return $this->avg_word_length;
    }

    /**
     * Generated from protobuf field <code>float avg_word_length = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setAvgWordLength($var)
    {
        GPBUtil::checkFloat($var);
        $this->avg_word_length = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string detected_language = 7;</code>
     * @return string
     */
    public function getDetectedLanguage()
    {
        return $this->detected_language;
    }

    /**
     * Generated from protobuf field <code>string detected_language = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setDetectedLanguage($var)
    {
        GPBUtil::checkString($var, True);
        $this->detected_language = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string top_words = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTopWords()
    {
        return $this->top_words;
    }

    /**
     * Generated from protobuf field <code>repeated string top_words = 8;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTopWords($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->top_words = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ai.AuthorMatch top_match = 9;</code>
     * @return \Ai\AuthorMatch|null
     */
    public function getTopMatch()
    {
        return $this->top_match;
    }

    public function hasTopMatch()
    {
        return isset($this->top_match);
    }

    public function clearTopMatch()
    {
        unset($this->top_match);
    }

    /**
     * Generated from protobuf field <code>.ai.AuthorMatch top_match = 9;</code>
     * @param \Ai\AuthorMatch $var
     * @return $this
     */
    public function setTopMatch($var)
    {
        GPBUtil::checkMessage($var, \Ai\AuthorMatch::class);
        $this->top_match = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .ai.AuthorMatch other_matches = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOtherMatches()
    {
        return $this->other_matches;
    }

    /**
     * Generated from protobuf field <code>repeated .ai.AuthorMatch other_matches = 10;</code>
     * @param array<\Ai\AuthorMatch>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOtherMatches($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ai\AuthorMatch::class);
        $this->other_matches = $arr;

        return $this;
    }

}

