<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai.proto

namespace Ai;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request to analyze writing style
 *
 * Generated from protobuf message <code>ai.WritingStyleRequest</code>
 */
class WritingStyleRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     */
    protected $user_id = '';
    /**
     * Array of journal entry texts
     *
     * Generated from protobuf field <code>repeated string texts = 2;</code>
     */
    private $texts;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $user_id
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $texts
     *           Array of journal entry texts
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ai::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Array of journal entry texts
     *
     * Generated from protobuf field <code>repeated string texts = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTexts()
    {
        return $this->texts;
    }

    /**
     * Array of journal entry texts
     *
     * Generated from protobuf field <code>repeated string texts = 2;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTexts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->texts = $arr;

        return $this;
    }

}

