// ESM wrapper for typing_pb.js (CommonJS generated file)
import * as jspb from 'google-protobuf';

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array
 * @extends {jspb.Message}
 * @constructor
 */
export class ClientTypingEvent extends jspb.Message {
  constructor(opt_data) {
    super();
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
  }

  static deserializeBinary(bytes) {
    const reader = new jspb.BinaryReader(bytes);
    const msg = new ClientTypingEvent();
    return ClientTypingEvent.deserializeBinaryFromReader(msg, reader);
  }

  static deserializeBinaryFromReader(msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      const field = reader.getFieldNumber();
      switch (field) {
        case 1:
          msg.setChannelId(reader.readString());
          break;
        case 2:
          msg.setIsTyping(reader.readBool());
          break;
        default:
          reader.skipField();
          break;
      }
    }
    return msg;
  }

  serializeBinary() {
    const writer = new jspb.BinaryWriter();
    ClientTypingEvent.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
  }

  static serializeBinaryToWriter(message, writer) {
    const channelId = message.getChannelId();
    if (channelId.length > 0) {
      writer.writeString(1, channelId);
    }
    const isTyping = message.getIsTyping();
    if (isTyping) {
      writer.writeBool(2, isTyping);
    }
  }

  getChannelId() {
    return jspb.Message.getFieldWithDefault(this, 1, '');
  }

  setChannelId(value) {
    return jspb.Message.setProto3StringField(this, 1, value);
  }

  getIsTyping() {
    return jspb.Message.getBooleanFieldWithDefault(this, 2, false);
  }

  setIsTyping(value) {
    return jspb.Message.setProto3BooleanField(this, 2, value);
  }
}

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array
 * @extends {jspb.Message}
 * @constructor
 */
export class ServerTypingEvent extends jspb.Message {
  constructor(opt_data) {
    super();
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
  }

  static deserializeBinary(bytes) {
    const reader = new jspb.BinaryReader(bytes);
    const msg = new ServerTypingEvent();
    return ServerTypingEvent.deserializeBinaryFromReader(msg, reader);
  }

  static deserializeBinaryFromReader(msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      const field = reader.getFieldNumber();
      switch (field) {
        case 1:
          msg.setUserId(reader.readString());
          break;
        case 2:
          msg.setUserName(reader.readString());
          break;
        case 3:
          msg.setChannelId(reader.readString());
          break;
        case 4:
          msg.setIsTyping(reader.readBool());
          break;
        case 5:
          msg.setTimestamp(reader.readInt64());
          break;
        default:
          reader.skipField();
          break;
      }
    }
    return msg;
  }

  serializeBinary() {
    const writer = new jspb.BinaryWriter();
    ServerTypingEvent.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
  }

  static serializeBinaryToWriter(message, writer) {
    const userId = message.getUserId();
    if (userId.length > 0) {
      writer.writeString(1, userId);
    }
    const userName = message.getUserName();
    if (userName.length > 0) {
      writer.writeString(2, userName);
    }
    const channelId = message.getChannelId();
    if (channelId.length > 0) {
      writer.writeString(3, channelId);
    }
    const isTyping = message.getIsTyping();
    if (isTyping) {
      writer.writeBool(4, isTyping);
    }
    const timestamp = message.getTimestamp();
    if (timestamp !== 0) {
      writer.writeInt64(5, timestamp);
    }
  }

  getUserId() {
    return jspb.Message.getFieldWithDefault(this, 1, '');
  }

  setUserId(value) {
    return jspb.Message.setProto3StringField(this, 1, value);
  }

  getUserName() {
    return jspb.Message.getFieldWithDefault(this, 2, '');
  }

  setUserName(value) {
    return jspb.Message.setProto3StringField(this, 2, value);
  }

  getChannelId() {
    return jspb.Message.getFieldWithDefault(this, 3, '');
  }

  setChannelId(value) {
    return jspb.Message.setProto3StringField(this, 3, value);
  }

  getIsTyping() {
    return jspb.Message.getBooleanFieldWithDefault(this, 4, false);
  }

  setIsTyping(value) {
    return jspb.Message.setProto3BooleanField(this, 4, value);
  }

  getTimestamp() {
    return jspb.Message.getFieldWithDefault(this, 5, 0);
  }

  setTimestamp(value) {
    return jspb.Message.setProto3IntField(this, 5, value);
  }
}
