<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InstansiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('instansi')->truncate();

        DB::table('instansi')->insert([
            [
                'id' => 1,
                'kategori' => 'Kementerian',
                'instansi' => 'Kementerian Dalam Negeri',
                'proses_bisnis_as_is' => 8,
                'layanan_as_is' => 8,
                'data_info_as_is' => 13,
                'aplikasi_as_is' => 2,
                'infra_as_is' => 4,
                'keamanan_as_is' => 1,
                'proses_bisnis_to_be' => 2,
                'layanan_to_be' => 3,
                'data_info_to_be' => 5,
                'aplikasi_to_be' => 2,
                'infra_to_be' => 1,
                'keamanan_to_be' => 0,
                'peta_rencana' => 0,
                'clearance' => 0,
                'reviueval' => 0,
                'tingkat_kematangan' => 0,
                'created_at' => '2025-10-06 00:14:18',
                'updated_at' => '2025-10-06 00:14:18',
            ],
            [
                'id' => 2,
                'kategori' => 'Kementerian',
                'instansi' => 'Kementerian Luar Negeri',
                'proses_bisnis_as_is' => 3,
                'layanan_as_is' => 6,
                'data_info_as_is' => 9,
                'aplikasi_as_is' => 6,
                'infra_as_is' => 2,
                'keamanan_as_is' => 4,
                'proses_bisnis_to_be' => 2,
                'layanan_to_be' => 3,
                'data_info_to_be' => 5,
                'aplikasi_to_be' => 1,
                'infra_to_be' => 1,
                'keamanan_to_be' => 2,
                'peta_rencana' => 0,
                'clearance' => 0,
                'reviueval' => 0,
                'tingkat_kematangan' => 0,
                'created_at' => '2025-10-06 00:14:19',
                'updated_at' => '2025-10-06 00:14:19',
            ],
            [
                'id' => 3,
                'kategori' => 'Kementerian',
                'instansi' => 'Kementerian Pertahanan',
                'proses_bisnis_as_is' => 8,
                'layanan_as_is' => 4,
                'data_info_as_is' => 15,
                'aplikasi_as_is' => 3,
                'infra_as_is' => 1,
                'keamanan_as_is' => 4,
                'proses_bisnis_to_be' => 1,
                'layanan_to_be' => 3,
                'data_info_to_be' => 5,
                'aplikasi_to_be' => 2,
                'infra_to_be' => 1,
                'keamanan_to_be' => 0,
                'peta_rencana' => 0,
                'clearance' => 0,
                'reviueval' => 0,
                'tingkat_kematangan' => 0,
                'created_at' => '2025-10-06 00:14:19',
                'updated_at' => '2025-10-06 00:14:19',
            ],
            [
                'id' => 4,
                'kategori' => 'Kementerian',
                'instansi' => 'Kementerian Agama',
                'proses_bisnis_as_is' => 5,
                'layanan_as_is' => 9,
                'data_info_as_is' => 6,
                'aplikasi_as_is' => 7,
                'infra_as_is' => 4,
                'keamanan_as_is' => 1,
                'proses_bisnis_to_be' => 4,
                'layanan_to_be' => 3,
                'data_info_to_be' => 3,
                'aplikasi_to_be' => 3,
                'infra_to_be' => 2,
                'keamanan_to_be' => 0,
                'peta_rencana' => 0,
                'clearance' => 0,
                'reviueval' => 0,
                'tingkat_kematangan' => 0,
                'created_at' => '2025-10-06 00:14:19',
                'updated_at' => '2025-10-06 00:14:19',
            ],
            [
                'id' => 5,
                'kategori' => 'Kementerian',
                'instansi' => 'Kementerian Hukum',
                'proses_bisnis_as_is' => 6,
                'layanan_as_is' => 10,
                'data_info_as_is' => 9,
                'aplikasi_as_is' => 6,
                'infra_as_is' => 2,
                'keamanan_as_is' => 4,
                'proses_bisnis_to_be' => 2,
                'layanan_to_be' => 1,
                'data_info_to_be' => 2,
                'aplikasi_to_be' => 1,
                'infra_to_be' => 1,
                'keamanan_to_be' => 2,
                'peta_rencana' => 0,
                'clearance' => 0,
                'reviueval' => 0,
                'tingkat_kematangan' => 0,
                'created_at' => '2025-10-06 00:14:19',
                'updated_at' => '2025-10-06 00:14:19',
            ],
            [
                'id' => 6,
                'kategori' => 'Kementerian',
                'instansi' => 'Kementerian Hak Asasi Manusia',
                'proses_bisnis_as_is' => 8,
                'layanan_as_is' => 8,
                'data_info_as_is' => 11,
                'aplikasi_as_is' => 6,
                'infra_as_is' => 4,
                'keamanan_as_is' => 2,
                'proses_bisnis_to_be' => 4,
                'layanan_to_be' => 1,
                'data_info_to_be' => 4,
                'aplikasi_to_be' => 3,
                'infra_to_be' => 2,
                'keamanan_to_be' => 1,
                'peta_rencana' => 0,
                'clearance' => 0,
                'reviueval' => 0,
                'tingkat_kematangan' => 0,
                'created_at' => '2025-10-06 00:14:19',
                'updated_at' => '2025-10-06 00:14:19',
            ],
            [
                'id' => 7,
                'kategori' => 'Kementerian',
                'instansi' => 'Kementerian Imigrasi dan Pemasyarakatan',
                'proses_bisnis_as_is' => 5,
                'layanan_as_is' => 5,
                'data_info_as_is' => 14,
                'aplikasi_as_is' => 7,
                'infra_as_is' => 2,
                'keamanan_as_is' => 4,
                'proses_bisnis_to_be' => 2,
                'layanan_to_be' => 3,
                'data_info_to_be' => 2,
                'aplikasi_to_be' => 1,
                'infra_to_be' => 1,
                'keamanan_to_be' => 0,
                'peta_rencana' => 0,
                'clearance' => 0,
                'reviueval' => 0,
                'tingkat_kematangan' => 0,
                'created_at' => '2025-10-06 00:14:19',
                'updated_at' => '2025-10-06 00:14:19',
            ],
            [
                'id' => 8,
                'kategori' => 'Kementerian',
                'instansi' => 'Kementerian Keuangan',
                'proses_bisnis_as_is' => 5,
                'layanan_as_is' => 9,
                'data_info_as_is' => 15,
                'aplikasi_as_is' => 4,
                'infra_as_is' => 1,
                'keamanan_as_is' => 4,
                'proses_bisnis_to_be' => 1,
                'layanan_to_be' => 3,
                'data_info_to_be' => 3,
                'aplikasi_to_be' => 1,
                'infra_to_be' => 2,
                'keamanan_to_be' => 1,
                'peta_rencana' => 0,
                'clearance' => 0,
                'reviueval' => 0,
                'tingkat_kematangan' => 0,
                'created_at' => '2025-10-06 00:14:19',
                'updated_at' => '2025-10-06 00:14:19',
            ],
            [
                'id' => 9,
                'kategori' => 'Kementerian',
                'instansi' => 'Kementerian Pendidikan Dasar dan Menengah',
                'proses_bisnis_as_is' => 3,
                'layanan_as_is' => 6,
                'data_info_as_is' => 14,
                'aplikasi_as_is' => 3,
                'infra_as_is' => 3,
                'keamanan_as_is' => 1,
                'proses_bisnis_to_be' => 3,
                'layanan_to_be' => 1,
                'data_info_to_be' => 2,
                'aplikasi_to_be' => 2,
                'infra_to_be' => 1,
                'keamanan_to_be' => 2,
                'peta_rencana' => 0,
                'clearance' => 0,
                'reviueval' => 0,
                'tingkat_kematangan' => 0,
                'created_at' => '2025-10-06 00:14:19',
                'updated_at' => '2025-10-06 00:14:19',
            ],
            [
                'id' => 10,
                'kategori' => 'Kementerian',
                'instansi' => 'Kementerian Pendidikan Tinggi, Sains, dan Teknologi',
                'proses_bisnis_as_is' => 4,
                'layanan_as_is' => 10,
                'data_info_as_is' => 7,
                'aplikasi_as_is' => 6,
                'infra_as_is' => 5,
                'keamanan_as_is' => 2,
                'proses_bisnis_to_be' => 2,
                'layanan_to_be' => 3,
                'data_info_to_be' => 4,
                'aplikasi_to_be' => 2,
                'infra_to_be' => 2,
                'keamanan_to_be' => 2,
                'peta_rencana' => 0,
                'clearance' => 0,
                'reviueval' => 0,
                'tingkat_kematangan' => 0,
                'created_at' => '2025-10-06 00:14:19',
                'updated_at' => '2025-10-06 00:14:19',
            ],
            [
                'id' => 11,
                'kategori' => 'Kementerian',
                'instansi' => 'Kementerian Kebudayaan',
                'proses_bisnis_as_is' => 7,
                'layanan_as_is' => 8,
                'data_info_as_is' => 14,
                'aplikasi_as_is' => 5,
                'infra_as_is' => 3,
                'keamanan_as_is' => 2,
                'proses_bisnis_to_be' => 1,
                'layanan_to_be' => 3,
                'data_info_to_be' => 4,
                'aplikasi_to_be' => 3,
                'infra_to_be' => 1,
                'keamanan_to_be' => 1,
                'peta_rencana' => 0,
                'clearance' => 0,
                'reviueval' => 0,
                'tingkat_kematangan' => 0,
                'created_at' => '2025-10-06 00:14:19',
                'updated_at' => '2025-10-06 00:14:19',
            ],
            [
                'id' => 12,
                'kategori' => 'LPNK',
                'instansi' => 'LPNK A',
                'proses_bisnis_as_is' => 5,
                'layanan_as_is' => 7,
                'data_info_as_is' => 10,
                'aplikasi_as_is' => 2,
                'infra_as_is' => 1,
                'keamanan_as_is' => 1,
                'proses_bisnis_to_be' => 2,
                'layanan_to_be' => 1,
                'data_info_to_be' => 3,
                'aplikasi_to_be' => 1,
                'infra_to_be' => 1,
                'keamanan_to_be' => 0,
                'peta_rencana' => 0,
                'clearance' => 0,
                'reviueval' => 0,
                'tingkat_kematangan' => 1,
                'created_at' => '2025-10-06 00:14:19',
                'updated_at' => '2025-10-06 00:14:19',
            ],
            [
                'id' => 13,
                'kategori' => 'LPNK',
                'instansi' => 'LPNK B',
                'proses_bisnis_as_is' => 8,
                'layanan_as_is' => 6,
                'data_info_as_is' => 12,
                'aplikasi_as_is' => 4,
                'infra_as_is' => 3,
                'keamanan_as_is' => 2,
                'proses_bisnis_to_be' => 4,
                'layanan_to_be' => 3,
                'data_info_to_be' => 5,
                'aplikasi_to_be' => 2,
                'infra_to_be' => 2,
                'keamanan_to_be' => 1,
                'peta_rencana' => 0,
                'clearance' => 0,
                'reviueval' => 1,
                'tingkat_kematangan' => 0,
                'created_at' => '2025-10-06 00:14:19',
                'updated_at' => '2025-10-06 00:14:19',
            ],
            [
                'id' => 14,
                'kategori' => 'LNS',
                'instansi' => 'LNS A',
                'proses_bisnis_as_is' => 6,
                'layanan_as_is' => 4,
                'data_info_as_is' => 9,
                'aplikasi_as_is' => 3,
                'infra_as_is' => 2,
                'keamanan_as_is' => 1,
                'proses_bisnis_to_be' => 2,
                'layanan_to_be' => 2,
                'data_info_to_be' => 3,
                'aplikasi_to_be' => 1,
                'infra_to_be' => 1,
                'keamanan_to_be' => 1,
                'peta_rencana' => 0,
                'clearance' => 0,
                'reviueval' => 0,
                'tingkat_kematangan' => 0,
                'created_at' => '2025-10-06 00:14:19',
                'updated_at' => '2025-10-06 00:14:19',
            ],
            [
                'id' => 15,
                'kategori' => 'LNS',
                'instansi' => 'LNS B',
                'proses_bisnis_as_is' => 4,
                'layanan_as_is' => 2,
                'data_info_as_is' => 7,
                'aplikasi_as_is' => 2,
                'infra_as_is' => 1,
                'keamanan_as_is' => 0,
                'proses_bisnis_to_be' => 1,
                'layanan_to_be' => 1,
                'data_info_to_be' => 2,
                'aplikasi_to_be' => 1,
                'infra_to_be' => 0,
                'keamanan_to_be' => 0,
                'peta_rencana' => 0,
                'clearance' => 0,
                'reviueval' => 0,
                'tingkat_kematangan' => 1,
                'created_at' => '2025-10-06 00:14:19',
                'updated_at' => '2025-10-06 00:14:19',
            ],
            [
                'id' => 16,
                'kategori' => 'Instansi Lain',
                'instansi' => 'Instansi Lain A',
                'proses_bisnis_as_is' => 3,
                'layanan_as_is' => 2,
                'data_info_as_is' => 5,
                'aplikasi_as_is' => 1,
                'infra_as_is' => 1,
                'keamanan_as_is' => 1,
                'proses_bisnis_to_be' => 2,
                'layanan_to_be' => 1,
                'data_info_to_be' => 2,
                'aplikasi_to_be' => 1,
                'infra_to_be' => 1,
                'keamanan_to_be' => 1,
                'peta_rencana' => 0,
                'clearance' => 0,
                'reviueval' => 0,
                'tingkat_kematangan' => 0,
                'created_at' => '2025-10-06 00:14:19',
                'updated_at' => '2025-10-06 00:14:19',
            ],
            [
                'id' => 17,
                'kategori' => 'Instansi Lain',
                'instansi' => 'Instansi Lain B',
                'proses_bisnis_as_is' => 7,
                'layanan_as_is' => 5,
                'data_info_as_is' => 11,
                'aplikasi_as_is' => 3,
                'infra_as_is' => 2,
                'keamanan_as_is' => 2,
                'proses_bisnis_to_be' => 3,
                'layanan_to_be' => 2,
                'data_info_to_be' => 4,
                'aplikasi_to_be' => 1,
                'infra_to_be' => 1,
                'keamanan_to_be' => 1,
                'peta_rencana' => 0,
                'clearance' => 0,
                'reviueval' => 1,
                'tingkat_kematangan' => 0,
                'created_at' => '2025-10-06 00:14:19',
                'updated_at' => '2025-10-06 00:14:19',
            ],
            [
                'id' => 18,
                'kategori' => 'Provinsi',
                'instansi' => 'Provinsi A',
                'proses_bisnis_as_is' => 9,
                'layanan_as_is' => 8,
                'data_info_as_is' => 15,
                'aplikasi_as_is' => 4,
                'infra_as_is' => 3,
                'keamanan_as_is' => 2,
                'proses_bisnis_to_be' => 4,
                'layanan_to_be' => 2,
                'data_info_to_be' => 5,
                'aplikasi_to_be' => 2,
                'infra_to_be' => 1,
                'keamanan_to_be' => 1,
                'peta_rencana' => 0,
                'clearance' => 0,
                'reviueval' => 1,
                'tingkat_kematangan' => 0,
                'created_at' => '2025-10-06 00:14:19',
                'updated_at' => '2025-10-06 00:14:19',
            ],
            [
                'id' => 19,
                'kategori' => 'Provinsi',
                'instansi' => 'Provinsi B',
                'proses_bisnis_as_is' => 2,
                'layanan_as_is' => 3,
                'data_info_as_is' => 6,
                'aplikasi_as_is' => 2,
                'infra_as_is' => 1,
                'keamanan_as_is' => 1,
                'proses_bisnis_to_be' => 1,
                'layanan_to_be' => 1,
                'data_info_to_be' => 2,
                'aplikasi_to_be' => 1,
                'infra_to_be' => 1,
                'keamanan_to_be' => 0,
                'peta_rencana' => 0,
                'clearance' => 0,
                'reviueval' => 0,
                'tingkat_kematangan' => 0,
                'created_at' => '2025-10-06 00:14:19',
                'updated_at' => '2025-10-06 00:14:19',
            ],
            [
                'id' => 20,
                'kategori' => 'Kab/Kota',
                'instansi' => 'Kabupaten/Kota A',
                'proses_bisnis_as_is' => 6,
                'layanan_as_is' => 4,
                'data_info_as_is' => 8,
                'aplikasi_as_is' => 2,
                'infra_as_is' => 1,
                'keamanan_as_is' => 1,
                'proses_bisnis_to_be' => 1,
                'layanan_to_be' => 1,
                'data_info_to_be' => 2,
                'aplikasi_to_be' => 1,
                'infra_to_be' => 1,
                'keamanan_to_be' => 0,
                'peta_rencana' => 0,
                'clearance' => 0,
                'reviueval' => 0,
                'tingkat_kematangan' => 0,
                'created_at' => '2025-10-06 00:14:19',
                'updated_at' => '2025-10-06 00:14:19',
            ],
            [
                'id' => 21,
                'kategori' => 'Kab/Kota',
                'instansi' => 'Kabupaten/Kota B',
                'proses_bisnis_as_is' => 4,
                'layanan_as_is' => 2,
                'data_info_as_is' => 10,
                'aplikasi_as_is' => 7,
                'infra_as_is' => 2,
                'keamanan_as_is' => 1,
                'proses_bisnis_to_be' => 3,
                'layanan_to_be' => 1,
                'data_info_to_be' => 2,
                'aplikasi_to_be' => 1,
                'infra_to_be' => 1,
                'keamanan_to_be' => 0,
                'peta_rencana' => 1,
                'clearance' => 0,
                'reviueval' => 0,
                'tingkat_kematangan' => 0,
                'created_at' => '2025-10-06 00:14:19',
                'updated_at' => '2025-10-06 00:14:19',
            ],
        ]);
    }
}
